# Chord: Cdim\A (variant 4)
# Type: Dim
# Description: До-уменьшенный с басом Ля

BACKGROUND_NAME = "griff"

FRETS = { '1LAD': { 'color': [0, 0, 0],
            'font_family': 'Arial',
            'size': 30,
            'style': 'default',
            'symbol': '7',
            'x': 220,
            'y': 30},
  '2LAD': { 'color': [0, 0, 0],
            'font_family': 'Arial',
            'size': 30,
            'style': 'default',
            'symbol': '8',
            'x': 560,
            'y': 30},
  '3LAD': { 'color': [0, 0, 0],
            'font_family': 'Arial',
            'size': 30,
            'style': 'default',
            'symbol': '9',
            'x': 870,
            'y': 30},
  '4LAD': { 'color': [0, 0, 0],
            'font_family': 'Arial',
            'size': 30,
            'style': 'default',
            'symbol': '10',
            'x': 1170,
            'y': 30}}

NOTES = { '11finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 112},
  '11finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 112},
  '11finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 112},
  '11finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 112},
  '11fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 112},
  '11noteB': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'B',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_B',
               'text_color': [0, 0, 0],
               'x': 224,
               'y': 112},
  '12finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 240},
  '12finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 240},
  '12finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 240},
  '12finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 240},
  '12fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 240},
  '12noteF#': { 'display_text': 'note_name',
                'finger': '',
                'font_style': 'bold',
                'note_name': 'F#',
                'outline': 'medium',
                'radius': 50,
                'style': 'note_F#',
                'text_color': [0, 0, 0],
                'x': 224,
                'y': 240},
  '13finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 370},
  '13finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 370},
  '13finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 370},
  '13finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 370},
  '13fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 370},
  '13noteD': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'D',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_D',
               'text_color': [0, 0, 0],
               'x': 224,
               'y': 370},
  '14finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 500},
  '14finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 500},
  '14finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 500},
  '14finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 500},
  '14fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 500},
  '14noteA': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'A',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_A',
               'text_color': [0, 0, 0],
               'x': 224,
               'y': 500},
  '15finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 630},
  '15finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 630},
  '15finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 630},
  '15finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 630},
  '15fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 630},
  '15noteE': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'E',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_E',
               'text_color': [0, 0, 0],
               'x': 224,
               'y': 630},
  '16finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 760},
  '16finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 760},
  '16finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 760},
  '16finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 760},
  '16fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 224,
                 'y': 760},
  '16noteB': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'B',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_B',
               'text_color': [0, 0, 0],
               'x': 224,
               'y': 760},
  '21finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 112},
  '21finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 112},
  '21finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 112},
  '21finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 112},
  '21fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 112},
  '21noteC': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'C',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_C',
               'text_color': [0, 0, 0],
               'x': 560,
               'y': 112},
  '22finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 240},
  '22finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 240},
  '22finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 240},
  '22finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 240},
  '22fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 240},
  '22noteG': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'G',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_G',
               'text_color': [0, 0, 0],
               'x': 560,
               'y': 240},
  '23finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 370},
  '23finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 370},
  '23finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 370},
  '23finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 370},
  '23fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 370},
  '23noteD#': { 'display_text': 'note_name',
                'finger': '',
                'font_style': 'bold',
                'note_name': 'D#',
                'outline': 'medium',
                'radius': 50,
                'style': 'note_D#',
                'text_color': [0, 0, 0],
                'x': 560,
                'y': 370},
  '24finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 500},
  '24finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 500},
  '24finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 500},
  '24finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 500},
  '24fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 500},
  '24noteA#': { 'display_text': 'note_name',
                'finger': '',
                'font_style': 'bold',
                'note_name': 'A#',
                'outline': 'medium',
                'radius': 50,
                'style': 'note_A#',
                'text_color': [0, 0, 0],
                'x': 560,
                'y': 500},
  '25finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 630},
  '25finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 630},
  '25finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 630},
  '25finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 630},
  '25fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 630},
  '25noteF': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'F',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_F',
               'text_color': [0, 0, 0],
               'x': 560,
               'y': 630},
  '26finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 760},
  '26finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 760},
  '26finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 760},
  '26finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 760},
  '26fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 560,
                 'y': 760},
  '26noteC': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'C',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_C',
               'text_color': [0, 0, 0],
               'x': 560,
               'y': 760},
  '31finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 112},
  '31finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 112},
  '31finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 112},
  '31finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 112},
  '31fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 112},
  '31noteC#': { 'display_text': 'note_name',
                'finger': '',
                'font_style': 'bold',
                'note_name': 'C#',
                'outline': 'medium',
                'radius': 50,
                'style': 'note_C#',
                'text_color': [0, 0, 0],
                'x': 870,
                'y': 112},
  '32finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 240},
  '32finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 240},
  '32finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 240},
  '32finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 240},
  '32fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 240},
  '32noteG#': { 'display_text': 'note_name',
                'finger': '',
                'font_style': 'bold',
                'note_name': 'G#',
                'outline': 'medium',
                'radius': 50,
                'style': 'note_G#',
                'text_color': [0, 0, 0],
                'x': 870,
                'y': 240},
  '33finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 370},
  '33finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 370},
  '33finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 370},
  '33finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 370},
  '33fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 370},
  '33noteE': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'E',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_E',
               'text_color': [0, 0, 0],
               'x': 870,
               'y': 370},
  '34finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 500},
  '34finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 500},
  '34finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 500},
  '34finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 500},
  '34fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 500},
  '34noteB': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'B',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_B',
               'text_color': [0, 0, 0],
               'x': 870,
               'y': 500},
  '35finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 630},
  '35finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 630},
  '35finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 630},
  '35finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 630},
  '35fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 630},
  '35noteF#': { 'display_text': 'note_name',
                'finger': '',
                'font_style': 'bold',
                'note_name': 'F#',
                'outline': 'medium',
                'radius': 50,
                'style': 'note_F#',
                'text_color': [0, 0, 0],
                'x': 870,
                'y': 630},
  '36finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 760},
  '36finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 760},
  '36finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 760},
  '36finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 760},
  '36fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 870,
                 'y': 760},
  '36noteC#': { 'display_text': 'note_name',
                'finger': '',
                'font_style': 'bold',
                'note_name': 'C#',
                'outline': 'medium',
                'radius': 50,
                'style': 'note_C#',
                'text_color': [0, 0, 0],
                'x': 870,
                'y': 760},
  '41finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 112},
  '41finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 112},
  '41finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 112},
  '41finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 112},
  '41fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 112},
  '41noteD': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'D',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_D',
               'text_color': [0, 0, 0],
               'x': 1170,
               'y': 112},
  '42finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 240},
  '42finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 240},
  '42finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 240},
  '42finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 240},
  '42fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 240},
  '42noteA': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'A',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_A',
               'text_color': [0, 0, 0],
               'x': 1170,
               'y': 240},
  '43finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 370},
  '43finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 370},
  '43finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 370},
  '43finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 370},
  '43fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 370},
  '43noteF': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'F',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_F',
               'text_color': [0, 0, 0],
               'x': 1170,
               'y': 370},
  '44finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 500},
  '44finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 500},
  '44finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 500},
  '44finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 500},
  '44fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 500},
  '44noteC': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'C',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_C',
               'text_color': [0, 0, 0],
               'x': 1170,
               'y': 500},
  '45finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 630},
  '45finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 630},
  '45finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 630},
  '45finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 630},
  '45fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 630},
  '45noteG': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'G',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_G',
               'text_color': [0, 0, 0],
               'x': 1170,
               'y': 630},
  '46finger1': { 'display_text': 'finger',
                 'finger': '1',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 760},
  '46finger2': { 'display_text': 'finger',
                 'finger': '2',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 760},
  '46finger3': { 'display_text': 'finger',
                 'finger': '3',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 760},
  '46finger4': { 'display_text': 'finger',
                 'finger': '4',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 760},
  '46fingerT': { 'display_text': 'finger',
                 'finger': 'T',
                 'font_style': 'bold',
                 'note_name': 'B',
                 'outline': 'medium',
                 'radius': 50,
                 'style': 'orange_3d',
                 'text_color': [0, 0, 0],
                 'x': 1170,
                 'y': 760},
  '46noteD': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'D',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_D',
               'text_color': [0, 0, 0],
               'x': 1170,
               'y': 760},
  'title1E': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'E',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_E',
               'text_color': [0, 0, 0],
               'x': 56,
               'y': 112},
  'title2B': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'B',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_B',
               'text_color': [0, 0, 0],
               'x': 56,
               'y': 240},
  'title3G': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'G',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_G',
               'text_color': [0, 0, 0],
               'x': 56,
               'y': 370},
  'title4D': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'D',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_D',
               'text_color': [0, 0, 0],
               'x': 56,
               'y': 500},
  'title5A': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'A',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_A',
               'text_color': [0, 0, 0],
               'x': 56,
               'y': 630},
  'title6E': { 'display_text': 'note_name',
               'finger': '',
               'font_style': 'bold',
               'note_name': 'E',
               'outline': 'medium',
               'radius': 50,
               'style': 'note_E',
               'text_color': [0, 0, 0],
               'x': 56,
               'y': 760}}

OPEN_NOTES = { '1X': { 'display_text': 'symbol',
          'font_style': 'bold',
          'note_name': '',
          'outline': 'medium',
          'radius': 50,
          'style': 'orange_3d',
          'symbol': 'X',
          'text_color': [0, 0, 0],
          'x': 56,
          'y': 112},
  '2X': { 'display_text': 'symbol',
          'font_style': 'bold',
          'note_name': '',
          'outline': 'medium',
          'radius': 50,
          'style': 'orange_3d',
          'symbol': 'X',
          'text_color': [0, 0, 0],
          'x': 56,
          'y': 240},
  '3X': { 'display_text': 'symbol',
          'font_style': 'bold',
          'note_name': '',
          'outline': 'medium',
          'radius': 50,
          'style': 'orange_3d',
          'symbol': 'X',
          'text_color': [0, 0, 0],
          'x': 56,
          'y': 370},
  '4X': { 'display_text': 'symbol',
          'font_style': 'bold',
          'note_name': '',
          'outline': 'medium',
          'radius': 50,
          'style': 'orange_3d',
          'symbol': 'X',
          'text_color': [0, 0, 0],
          'x': 56,
          'y': 500},
  '5X': { 'display_text': 'symbol',
          'font_style': 'bold',
          'note_name': '',
          'outline': 'medium',
          'radius': 50,
          'style': 'orange_3d',
          'symbol': 'X',
          'text_color': [0, 0, 0],
          'x': 56,
          'y': 630},
  '6X': { 'display_text': 'symbol',
          'font_style': 'bold',
          'note_name': '',
          'outline': 'medium',
          'radius': 50,
          'style': 'orange_3d',
          'symbol': 'X',
          'text_color': [0, 0, 0],
          'x': 56,
          'y': 760}}

BARRES = { '1BAR1-2': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 80},
  '1BAR1-3': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 80},
  '1BAR1-4': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 80},
  '1BAR1-5': { 'color': [139, 69, 19],
               'height': 580,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 80},
  '1BAR1-6': { 'color': [139, 69, 19],
               'height': 730,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 80},
  '1BAR2-3': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 210},
  '1BAR2-4': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 210},
  '1BAR2-5': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 210},
  '1BAR2-6': { 'color': [139, 69, 19],
               'height': 590,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 210},
  '1BAR3-4': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 340},
  '1BAR3-5': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 340},
  '1BAR3-6': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 340},
  '1BAR4-5': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 470},
  '1BAR5-6': { 'color': [139, 69, 19],
               'height': 200,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 174,
               'y': 590},
  '2BAR1-2': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 80},
  '2BAR1-3': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 80},
  '2BAR1-4': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 80},
  '2BAR1-5': { 'color': [139, 69, 19],
               'height': 580,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 80},
  '2BAR1-6': { 'color': [139, 69, 19],
               'height': 730,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 80},
  '2BAR2-3': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 210},
  '2BAR2-4': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 210},
  '2BAR2-5': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 210},
  '2BAR2-6': { 'color': [139, 69, 19],
               'height': 590,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 210},
  '2BAR3-4': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 340},
  '2BAR3-5': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 340},
  '2BAR3-6': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 340},
  '2BAR4-5': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 470},
  '2BAR5-6': { 'color': [139, 69, 19],
               'height': 200,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 510,
               'y': 590},
  '3BAR1-2': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 80},
  '3BAR1-3': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 80},
  '3BAR1-4': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 80},
  '3BAR1-5': { 'color': [139, 69, 19],
               'height': 580,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 80},
  '3BAR1-6': { 'color': [139, 69, 19],
               'height': 730,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 80},
  '3BAR2-3': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 210},
  '3BAR2-4': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 210},
  '3BAR2-5': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 210},
  '3BAR2-6': { 'color': [139, 69, 19],
               'height': 590,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 210},
  '3BAR3-4': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 340},
  '3BAR3-5': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 340},
  '3BAR3-6': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 340},
  '3BAR4-5': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 470},
  '3BAR5-6': { 'color': [139, 69, 19],
               'height': 200,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 820,
               'y': 590},
  '4BAR1-2': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 80},
  '4BAR1-3': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 80},
  '4BAR1-4': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 80},
  '4BAR1-5': { 'color': [139, 69, 19],
               'height': 580,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 80},
  '4BAR1-6': { 'color': [139, 69, 19],
               'height': 730,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 80},
  '4BAR2-3': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 210},
  '4BAR2-4': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 210},
  '4BAR2-5': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 210},
  '4BAR2-6': { 'color': [139, 69, 19],
               'height': 590,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 210},
  '4BAR3-4': { 'color': [139, 69, 19],
               'height': 190,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 340},
  '4BAR3-5': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 340},
  '4BAR3-6': { 'color': [139, 69, 19],
               'height': 450,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 340},
  '4BAR4-5': { 'color': [139, 69, 19],
               'height': 320,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 470},
  '4BAR5-6': { 'color': [139, 69, 19],
               'height': 200,
               'outline': 'thin',
               'radius': 50,
               'style': 'wood',
               'width': 100,
               'x': 1120,
               'y': 590}}

SELECTED_FINGER = [ 'title2B',
  '6X',
  '14finger1',
  '12finger1',
  '23finger2',
  'title1E',
  'title3G',
  '21finger3',
  'title4D',
  '5X',
  '1BAR1-4']

SELECTED_NOTE = [ 'title2B',
  '6X',
  '12noteF#',
  'title1E',
  'title3G',
  '21noteC',
  'title4D',
  '14noteA',
  '5X',
  '23noteD#']

METADATA = { 'description': 'До-уменьшенный с басом Ля',
  'name': 'Cdim\\A',
  'type': 'Dim',
  'variant': 4}